export default {
    'iObserve' :{
        nodeGroupTextColor : '#333399',
        nodeGroupColor : 'white',
        nodeGroupBorderColor : '#333399',
        nodeTextColor : '#333399',
        nodeColor : 'white',
        nodeBorderColor : '#333399',
        serviceTextColor : '#333399',
        serviceColor : 'white',
        serviceBorderColor : '#AAA',
        arrowLineColor : '#AAA',
        arrowColor : '#AAA',
        arrowLabelColor: '#333399'
    },
    'arctic': {
        nodeGroupTextColor: '#3399CC',
        nodeGroupColor: 'white',
        nodeGroupBorderColor: '#39588A',
        nodeTextColor: '#3399CC',
        nodeColor: '#B4DCED',
        nodeBorderColor : '#B4DCED',
        serviceTextColor: '#3399CC',
        serviceColor: '#E8F8FF',
        serviceBorderColor : '#E8F8FF',
        arrowLineColor: '#3399CC',
        arrowColor: '#3399CC',
        arrowLabelColor: 'black'
    },
    'orange' :{
        nodeGroupTextColor : '#002A4A',
        nodeGroupColor : 'white',
        nodeGroupBorderColor : '#D64700',
        nodeTextColor : '#002A4A',
        nodeColor : '#17607D',
        nodeBorderColor : '#17607D',
        serviceTextColor : '#FFFEED',
        serviceColor : '#ED8910',
        serviceBorderColor : '#ED8910',
        arrowLineColor : '#002A4A',
        arrowColor : '#002A4A',
        arrowLabelColor: '#FFFEED'
    },
    'forest' :{
        nodeGroupTextColor : '#36231B',
        nodeGroupColor : 'white',
        nodeGroupBorderColor : '#60311F',
        nodeTextColor : '#36231B',
        nodeColor : '#8C5D42',
        nodeBorderColor : '#8C5D42',
        serviceTextColor : '#F0E3CA',
        serviceColor : '#93A608',
        serviceBorderColor : '#93A608',
        arrowLineColor : '#36231B',
        arrowColor : '#36231B',
        arrowLabelColor: '#F0E3CA'
    },
    'maritim' :{
        // https://color.adobe.com/RportalNew-color-theme-199478/
        nodeGroupTextColor : '#1D3757',
        nodeGroupColor : 'white',
        nodeGroupBorderColor : '#1D3757',
        nodeTextColor : '#1D3757',
        nodeColor : '#91BED4',
        nodeBorderColor : '#91BED4',
        serviceTextColor : '#D9E8F5',
        serviceColor : '#F29F01',
        serviceBorderColor : '#F29F01',
        arrowLineColor : '#1D3757',
        arrowColor : '#1D3757',
        arrowLabelColor: '#D9E8F5'
    },
    'green' :{
        // https://color.adobe.com/green-color-theme-1205538/
        nodeGroupTextColor : '#403E21',
        nodeGroupColor : 'white',
        nodeGroupBorderColor : '#403E21',
        nodeTextColor : '#403E21',
        nodeColor : '#70732F',
        nodeBorderColor : '#70732F',
        serviceTextColor : '#403E21',
        serviceColor : '#AABF8A',
        serviceBorderColor : '#AABF8A',
        arrowLineColor : '#89888C',
        arrowColor : '#89888C',
        arrowLabelColor: '#403E21'
    },
    'explorviz' :{
        nodeGroupTextColor : 'black',
        nodeGroupColor : '#c7c7c7',
        nodeGroupBorderColor : '#c7c7c7',
        nodeTextColor : 'black',
        nodeColor : '#00bb41',
        nodeBorderColor : '#00bb41',
        serviceTextColor : 'white',
        serviceColor : '#613eb4',
        serviceBorderColor : '#613eb4',
        arrowLineColor : '#f2901c',
        arrowColor : '#f2901c',
        arrowLabelColor: 'black'
    }
};
